"use client";

import { useState, useEffect, useMemo } from 'react';
import { useRouter } from 'next/navigation';
import { database } from '@/lib/firebase';
import { ref, onValue } from 'firebase/database';
import { useBullyingStore, ReportStatus } from '@/store/useBullyingStore';
import { useStudentStore } from '@/store/useStudentStore';
import { useClassStore } from '@/store/useClassStore';
import { useAuthStore } from '@/store/useAuthStore';
import { useTeacherStore } from '@/store/useTeacherStore';
import { format } from 'date-fns';
import { id } from 'date-fns/locale';
import { exportToExcel } from '@/utils/export';
import { 
  ShieldAlert, 
  MessageSquareWarning, 
  UserRound, 
  Clock, 
  CheckCircle2, 
  AlertTriangle,
  Search,
  ChevronDown,
  Info,
  Megaphone,
  ArrowLeft,
  Check
} from 'lucide-react';
import { edulockAuth } from '@/lib/edulockFirebase';

const callBullyingAdminApi = async (
  payload: Record<string, unknown>
) => {
  const currentUser = edulockAuth.currentUser;
  if (!currentUser) {
    throw new Error("Sesi admin tidak aktif. Silakan login ulang.");
  }

  const idToken = await currentUser.getIdToken();
  const response = await fetch("/api/admin/bullying-reports", {
    method: "PUT",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${idToken}`,
    },
    body: JSON.stringify(payload),
  });

  const result = await response.json().catch(() => ({}));
  if (!response.ok || result?.success === false) {
    throw new Error(String(result?.message || "Permintaan backend laporan aduan gagal diproses."));
  }

  return result;
};

export default function HaloSpentgapaPage() {
  const router = useRouter();
  const { user } = useAuthStore();
  const { reports, updateReportStatus, syncAndroidReports } = useBullyingStore();
  const { students, getStudentById } = useStudentStore();
  const { teachers, subscribeToTeachers } = useTeacherStore();
  const { classes } = useClassStore();

  const normalizeIdentity = (value: unknown) => String(value || '').trim();

  useEffect(() => {
    const unsub = subscribeToTeachers();
    return () => unsub();
  }, [subscribeToTeachers]);

  const teacherClassName = useMemo(() => {
    if (user?.role === 'teacher') {
      const me = teachers.find(t => t.nuptk === user.id);
      return me?.homeroomClass || null;
    }
    return null;
  }, [user, teachers]);

  const [activeTab, setActiveTab] = useState<'BULLYING' | 'INCIDENT'>('BULLYING');
  const [statusFilter, setStatusFilter] = useState<'ALL' | ReportStatus>('ALL');
  const [classFilter, setClassFilter] = useState<string>('ALL');

  const [studentTab, setStudentTab] = useState<'LAYANAN' | 'RIWAYAT'>('LAYANAN');
  const [selectedService, setSelectedService] = useState<'BULLYING' | 'INCIDENT' | null>(null);
  const { addReport } = useBullyingStore();
  const studentByIdentity = useMemo(() => {
    const lookup = new Map<string, (typeof students)[number]>();
    students.forEach((student) => {
      [normalizeIdentity(student.id), normalizeIdentity(student.nisn)]
        .filter(Boolean)
        .forEach((candidate) => {
          if (!lookup.has(candidate)) {
            lookup.set(candidate, student);
          }
        });
    });
    return lookup;
  }, [students]);
  const studentIdentitySet = useMemo(() => {
    const ids = new Set<string>();
    students.forEach((student) => {
      if (student.id) ids.add(normalizeIdentity(student.id));
      if (student.nisn) ids.add(normalizeIdentity(student.nisn));
    });
    return ids;
  }, [students]);
  
  // Form State
  const [formData, setFormData] = useState({
    description: '',
    location: '',
    date: new Date().toISOString().slice(0, 16), // YYYY-MM-DDTHH:mm
    type: '',
    isAnonymous: false,
    victimName: '',
    perpetratorName: ''
  });
  const [isSubmitting, setIsSubmitting] = useState(false);

  const updateAdminReportStatus = async (id: string, status: ReportStatus) => {
    try {
      await callBullyingAdminApi({
        action: "update-status",
        id,
        status,
      });
    } catch (error: any) {
      console.error(error);
      alert(String(error?.message || error || "Gagal memperbarui status laporan."));
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedService || !user) return;
    
    setIsSubmitting(true);
    try {
        await addReport({
            id: '', // Generated by store
            reporterId: normalizeIdentity(user.id || user.nisn), // Use stable student identity from session
            reporterName: user.name,
            isAnonymous: formData.isAnonymous,
            victimName: formData.victimName,
            perpetratorName: formData.perpetratorName,
            incidentDate: new Date(formData.date).getTime(),
            incidentLocation: formData.location,
            incidentType: formData.type as any,
            category: selectedService,
            description: formData.description,
            status: 'PENDING',
            priority: 'MEDIUM',
            createdAt: Date.now(),
            updatedAt: Date.now()
        });
        
        // Reset and go to history
        setFormData({
            description: '',
            location: '',
            date: new Date().toISOString().slice(0, 16),
            type: '',
            isAnonymous: false,
            victimName: '',
            perpetratorName: ''
        });
        setSelectedService(null);
        setStudentTab('RIWAYAT');
        alert('Laporan berhasil dikirim!');
    } catch (error) {
        console.error(error);
        alert('Gagal mengirim laporan.');
    } finally {
        setIsSubmitting(false);
    }
  };

  // Firebase Sync
  useEffect(() => {
    const reportsRef = ref(database, 'bullying_reports');
    const unsubscribe = onValue(reportsRef, (snapshot) => {
      const data = snapshot.val();
      if (data) {
        const loadedReports: any[] = [];
        Object.keys(data).forEach(key => {
          const item = data[key];
          loadedReports.push({
            id: key,
            ...item
          });
        });
        
        // Transform to store format
        const formattedReports = loadedReports.map(r => {
            const reporter = r.reporterId ? getStudentById(r.reporterId) : null;
            let reporterNameDisplay = r.reporterName || "Siswa";
            if (r.isAnonymous) {
              if (reporterNameDisplay === "Anonim" && reporter) {
                 reporterNameDisplay = `${reporter.name} (Anonim)`;
              } else if (reporterNameDisplay !== "Anonim") {
                 reporterNameDisplay = `${reporterNameDisplay} (Anonim)`;
              }
            } else if (reporter) {
              reporterNameDisplay = reporter.name;
            }

            return {
              id: r.id, 
              reporterId: r.reporterId, 
              reporterName: reporterNameDisplay,
              isAnonymous: r.isAnonymous,
              victimId: r.victimId,
              victimName: r.victimName,
              perpetratorId: r.perpetratorId,
              perpetratorName: r.perpetratorName,
              incidentDate: r.incidentDate,
              incidentLocation: r.incidentLocation,
              incidentType: r.incidentType,
              category: r.category || 'BULLYING',
              description: r.description,
              status: r.status,
              priority: r.priority,
              assignedTo: r.assignedTo,
              resolutionNotes: r.resolutionNotes,
              resolvedAt: r.resolvedAt,
              createdAt: r.createdAt,
              updatedAt: r.updatedAt || r.createdAt
            };
        });

        syncAndroidReports(formattedReports);
      }
    });

    return () => unsubscribe();
  }, [syncAndroidReports, getStudentById]);

  const scopedReports = useMemo(() => {
    if (user?.role === "super_admin" || user?.role === "student") return reports;
    return reports.filter((report) =>
      [report.reporterId, report.victimId, report.perpetratorId].some(
        (value) => value && studentIdentitySet.has(normalizeIdentity(value))
      )
    );
  }, [reports, studentIdentitySet, user?.role]);

  // Filter Logic
  const filteredReports = scopedReports.filter(report => {
    // 0. Student Filter: Show only my reports
    if (user?.role === 'student') {
        // Check if I am reporter
        if (
          ![normalizeIdentity(user.id), normalizeIdentity(user.nisn)]
            .filter(Boolean)
            .includes(normalizeIdentity(report.reporterId))
        ) return false;
    }

    // 1. Category Filter
    if (activeTab === 'BULLYING') {
       if (report.category && report.category !== 'BULLYING') return false;
    } else {
       if (report.category !== 'INCIDENT') return false;
    }

    // 2. Class Filter (if teacher)
    if (teacherClassName) {
       const reporter = report.reporterId ? studentByIdentity.get(normalizeIdentity(report.reporterId)) : null;
       const victim = report.victimId ? studentByIdentity.get(normalizeIdentity(report.victimId)) : null;
       const perpetrator = report.perpetratorId ? studentByIdentity.get(normalizeIdentity(report.perpetratorId)) : null;

       const reporterClass = reporter?.class || "";
       const victimClass = victim?.class || "";
       const perpetratorClass = perpetrator?.class || "";
       
       // Check if ANY of the involved parties are in the teacher's class
       const isRelevant = 
          (reporterClass === teacherClassName) || 
          (victimClass === teacherClassName) || 
          (perpetratorClass === teacherClassName);
          
       if (!isRelevant) return false;
    }

    // 3. Class Filter (Admin)
    if ((user?.role === "admin" || user?.role === "super_admin") && classFilter !== "ALL") {
      const reporter = report.reporterId ? studentByIdentity.get(normalizeIdentity(report.reporterId)) : null;
      const victim = report.victimId ? studentByIdentity.get(normalizeIdentity(report.victimId)) : null;
      const perpetrator = report.perpetratorId ? studentByIdentity.get(normalizeIdentity(report.perpetratorId)) : null;

      const reporterClass = reporter?.class || "";
      const victimClass = victim?.class || "";
      const perpetratorClass = perpetrator?.class || "";

      const isInClass =
        reporterClass === classFilter ||
        victimClass === classFilter ||
        perpetratorClass === classFilter;

      if (!isInClass) return false;
    }

    return true;
  }, [activeTab, classFilter, studentByIdentity, user]);

  const adminReports = useMemo(() => {
    if (statusFilter === 'ALL') return filteredReports;
    return filteredReports.filter(r => r.status === statusFilter);
  }, [filteredReports, statusFilter]);

  const classRecap = useMemo(() => {
    if (user?.role !== "admin" && user?.role !== "super_admin") return null;
    if (classFilter === 'ALL') return null;

    const reportsInClass = scopedReports.filter(report => {
      const reporter = report.reporterId ? studentByIdentity.get(normalizeIdentity(report.reporterId)) : null;
      const victim = report.victimId ? studentByIdentity.get(normalizeIdentity(report.victimId)) : null;
      const perpetrator = report.perpetratorId ? studentByIdentity.get(normalizeIdentity(report.perpetratorId)) : null;

      const reporterClass = reporter?.class || "";
      const victimClass = victim?.class || "";
      const perpetratorClass = perpetrator?.class || "";

      const isInClass =
        reporterClass === classFilter ||
        victimClass === classFilter ||
        perpetratorClass === classFilter;

      if (!isInClass) return false;

      if (activeTab === 'BULLYING') {
        if (report.category && report.category !== 'BULLYING') return false;
      } else {
        if (report.category !== 'INCIDENT') return false;
      }

      return true;
    });

    const total = reportsInClass.length;
    const bullying = reportsInClass.filter(r => (r.category || 'BULLYING') === 'BULLYING').length;
    const incident = reportsInClass.filter(r => r.category === 'INCIDENT').length;
    const pending = reportsInClass.filter(r => r.status === 'PENDING').length;
    const investigating = reportsInClass.filter(r => r.status === 'INVESTIGATING').length;
    const resolved = reportsInClass.filter(r => r.status === 'RESOLVED').length;
    const closed = reportsInClass.filter(r => r.status === 'CLOSED').length;

    return {
      total,
      bullying,
      incident,
      pending,
      investigating,
      resolved,
      closed
    };
  }, [user, classFilter, scopedReports, studentByIdentity, activeTab]);

  const handleExportAdmin = () => {
    if (user?.role !== "admin" && user?.role !== "super_admin") return;
    const data = adminReports.map(report => {
      const reporter = report.reporterId ? studentByIdentity.get(normalizeIdentity(report.reporterId)) : null;
      const victim = report.victimId ? studentByIdentity.get(normalizeIdentity(report.victimId)) : null;
      const perpetrator = report.perpetratorId ? studentByIdentity.get(normalizeIdentity(report.perpetratorId)) : null;

      const reporterClass = reporter?.class || "";

      return {
        Tanggal: new Date(report.incidentDate).toLocaleString('id-ID'),
        Kategori: report.category === 'BULLYING' ? 'Bullying' : 'Peristiwa',
        Jenis: getIncidentLabel(report.incidentType),
        Pelapor: report.reporterName,
        KelasPelapor: reporterClass,
        Korban: report.victimName || '-',
        Pelaku: report.perpetratorName || '-',
        Lokasi: report.incidentLocation || '-',
        Deskripsi: report.description || '',
        Status: report.status,
        CatatanPenanganan: report.resolutionNotes || ''
      };
    });

    const fileClass =
      classFilter === 'ALL' ? 'Semua_Kelas' : classFilter.replace(/\s+/g, '_');
    const fileCategory = activeTab === 'BULLYING' ? 'Bullying' : 'Peristiwa';

    exportToExcel(data, `Laporan_Layanan_Aduan_${fileCategory}_${fileClass}`);
  };

  const getIncidentLabel = (type: string) => {
    const types: Record<string, string> = {
      'VERBAL': 'Verbal',
      'PHYSICAL': 'Fisik',
      'CYBER': 'Siber',
      'SOCIAL': 'Sosial',
      'SEXUAL': 'Seksual',
      'TAWURAN': 'Tawuran',
      'KECELAKAAN': 'Kecelakaan',
      'KEHILANGAN': 'Kehilangan',
      'KERUSAKAN_FASILITAS': 'Kerusakan Fasilitas',
      'OTHER': 'Lainnya',
      'LAINNYA': 'Lainnya'
    };
    return types[type] || type;
  };

  // STUDENT VIEW
  if (user?.role === 'student') {
    return (
      <div className="min-h-screen bg-slate-900/30 -mx-4 -mt-4 sm:-mx-8 sm:-mt-8">
        {/* Header */}
        <div className="glass-effect-dark-card border-b border-slate-700 sticky top-0 z-10">
          <div className="px-4 py-4 flex items-center gap-3">
             {selectedService ? (
                 <button onClick={() => setSelectedService(null)} className="p-1 -ml-1">
                    <ArrowLeft className="w-6 h-6 text-slate-300" />
                 </button>
             ) : null}
             <h1 className="text-xl font-bold text-slate-100">Layanan Aduan</h1>
          </div>
          
          {/* Tabs - Only show if not in form mode */}
          {!selectedService && (
            <div className="flex px-4">
                <button
                    onClick={() => setStudentTab('LAYANAN')}
                    className={`flex-1 pb-3 text-sm font-bold border-b-2 transition-colors ${
                    studentTab === 'LAYANAN'
                        ? 'border-blue-600 text-blue-600'
                        : 'border-transparent text-slate-400 hover:text-slate-300'
                    }`}
                >
                    Layanan
                </button>
                <button
                    onClick={() => setStudentTab('RIWAYAT')}
                    className={`flex-1 pb-3 text-sm font-bold border-b-2 transition-colors ${
                    studentTab === 'RIWAYAT'
                        ? 'border-blue-600 text-blue-600'
                        : 'border-transparent text-slate-400 hover:text-slate-300'
                    }`}
                >
                    Riwayat Laporan
                </button>
            </div>
          )}
        </div>

        <div className="p-4 max-w-lg mx-auto">
            {studentTab === 'LAYANAN' && !selectedService && (
                <div className="space-y-6">
                    <div className="text-center py-4">
                        <h2 className="text-lg font-bold text-slate-100">Layanan Pengaduan Siswa</h2>
                        <p className="text-sm text-slate-400 mt-1 max-w-xs mx-auto">
                            Pilih jenis laporan yang ingin Anda sampaikan. Identitas Anda aman.
                        </p>
                    </div>

                    <button 
                        onClick={() => setSelectedService('BULLYING')}
                        className="w-full glass-effect-dark-card p-6 rounded-2xl shadow-sm border border-slate-700 flex items-start gap-4 hover:bg-slate-900/30 transition-colors text-left"
                    >
                        <div className="w-12 h-12 bg-red-50 rounded-xl flex items-center justify-center flex-shrink-0">
                            <AlertTriangle className="w-6 h-6 text-red-500" />
                        </div>
                        <div>
                            <h3 className="font-bold text-slate-100 text-lg">Lapor Bullying</h3>
                            <p className="text-sm text-slate-400 mt-1 leading-relaxed">
                                Laporkan tindakan perundungan (bullying) fisik, verbal, atau cyber.
                            </p>
                        </div>
                    </button>

                    <button 
                        onClick={() => setSelectedService('INCIDENT')}
                        className="w-full glass-effect-dark-card p-6 rounded-2xl shadow-sm border border-slate-700 flex items-start gap-4 hover:bg-slate-900/30 transition-colors text-left"
                    >
                        <div className="w-12 h-12 bg-orange-50 rounded-xl flex items-center justify-center flex-shrink-0">
                            <Info className="w-6 h-6 text-orange-500" />
                        </div>
                        <div>
                            <h3 className="font-bold text-slate-100 text-lg">Lapor Peristiwa</h3>
                            <p className="text-sm text-slate-400 mt-1 leading-relaxed">
                                Laporkan kejadian lain seperti tawuran, kecelakaan, kehilangan, atau kerusakan fasilitas.
                            </p>
                        </div>
                    </button>
                </div>
            )}

            {studentTab === 'LAYANAN' && selectedService && (
                <form onSubmit={handleSubmit} className="space-y-6 glass-effect-dark-card p-6 rounded-xl shadow-sm border border-slate-700">
                    <div className="border-b border-slate-700 pb-4 mb-4">
                        <h2 className="text-xl font-bold text-slate-100">
                            {selectedService === 'BULLYING' ? 'Formulir Lapor Bullying' : 'Formulir Lapor Peristiwa'}
                        </h2>
                        <p className="text-sm text-slate-400 mt-1">
                            Silakan isi data berikut dengan benar.
                        </p>
                    </div>

                    <div className="space-y-4">
                        <div>
                            <label className="block text-sm font-medium text-slate-300 mb-1">
                                Jenis {selectedService === 'BULLYING' ? 'Perundungan' : 'Peristiwa'}
                            </label>
                            <select
                                required
                                value={formData.type}
                                onChange={(e) => setFormData({...formData, type: e.target.value})}
                                className="w-full p-3 bg-slate-900/30 border border-slate-700 rounded-lg text-sm focus:ring-2 focus:ring-blue-500 outline-none text-slate-100"
                            >
                                <option value="">Pilih Jenis...</option>
                                {selectedService === 'BULLYING' ? (
                                    <>
                                        <option value="VERBAL">Verbal (Ejekan/Hinaan)</option>
                                        <option value="PHYSICAL">Fisik (Pukulan/Dorongan)</option>
                                        <option value="CYBER">Cyber (Media Sosial)</option>
                                        <option value="SOCIAL">Sosial (Pengucilan)</option>
                                        <option value="SEXUAL">Seksual</option>
                                    </>
                                ) : (
                                    <>
                                        <option value="TAWURAN">Tawuran</option>
                                        <option value="KECELAKAAN">Kecelakaan</option>
                                        <option value="KEHILANGAN">Kehilangan Barang</option>
                                        <option value="KERUSAKAN_FASILITAS">Kerusakan Fasilitas</option>
                                        <option value="LAINNYA">Lainnya</option>
                                    </>
                                )}
                            </select>
                        </div>

                        <div>
                            <label className="block text-sm font-medium text-slate-300 mb-1">
                                Tanggal Kejadian
                            </label>
                            <input
                                type="datetime-local"
                                required
                                value={formData.date}
                                onChange={(e) => setFormData({...formData, date: e.target.value})}
                                className="w-full p-3 bg-slate-900/30 border border-slate-700 rounded-lg text-sm focus:ring-2 focus:ring-blue-500 outline-none text-slate-100"
                            />
                        </div>

                        <div>
                            <label className="block text-sm font-medium text-slate-300 mb-1">
                                Lokasi Kejadian
                            </label>
                            <input
                                type="text"
                                required
                                placeholder="Contoh: Kantin, Kelas 7A, Parkiran"
                                value={formData.location}
                                onChange={(e) => setFormData({...formData, location: e.target.value})}
                                className="w-full p-3 bg-slate-900/30 border border-slate-700 rounded-lg text-sm focus:ring-2 focus:ring-blue-500 outline-none text-slate-100"
                            />
                        </div>

                        {selectedService === 'BULLYING' && (
                            <>
                                <div>
                                    <label className="block text-sm font-medium text-slate-300 mb-1">
                                        Nama Korban (Opsional)
                                    </label>
                                    <input
                                        type="text"
                                        placeholder="Kosongkan jika Anda sendiri"
                                        value={formData.victimName}
                                        onChange={(e) => setFormData({...formData, victimName: e.target.value})}
                                        className="w-full p-3 bg-slate-900/30 border border-slate-700 rounded-lg text-sm focus:ring-2 focus:ring-blue-500 outline-none text-slate-100"
                                    />
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-slate-300 mb-1">
                                        Nama Pelaku (Jika Tahu)
                                    </label>
                                    <input
                                        type="text"
                                        placeholder="Nama siswa yang melakukan"
                                        value={formData.perpetratorName}
                                        onChange={(e) => setFormData({...formData, perpetratorName: e.target.value})}
                                        className="w-full p-3 bg-slate-900/30 border border-slate-700 rounded-lg text-sm focus:ring-2 focus:ring-blue-500 outline-none text-slate-100"
                                    />
                                </div>
                            </>
                        )}

                        <div>
                            <label className="block text-sm font-medium text-slate-300 mb-1">
                                Deskripsi Kejadian
                            </label>
                            <textarea
                                required
                                rows={4}
                                placeholder="Ceritakan kronologi kejadian secara detail..."
                                value={formData.description}
                                onChange={(e) => setFormData({...formData, description: e.target.value})}
                                className="w-full p-3 bg-slate-900/30 border border-slate-700 rounded-lg text-sm focus:ring-2 focus:ring-blue-500 outline-none text-slate-100"
                            />
                        </div>

                        <div className="flex items-center gap-2 pt-2">
                            <input
                                type="checkbox"
                                id="anon"
                                checked={formData.isAnonymous}
                                onChange={(e) => setFormData({...formData, isAnonymous: e.target.checked})}
                                className="w-4 h-4 text-blue-600 rounded border-gray-300 focus:ring-blue-500"
                            />
                            <label htmlFor="anon" className="text-sm text-slate-300 select-none">
                                Laporkan secara anonim (Nama saya disembunyikan)
                            </label>
                        </div>
                    </div>

                    <button
                        type="submit"
                        disabled={isSubmitting}
                        className="w-full py-3.5 bg-blue-600 text-white rounded-xl font-bold shadow-lg hover:bg-blue-700 transition-all active:scale-95 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                        {isSubmitting ? 'Mengirim...' : 'Kirim Laporan'}
                    </button>
                </form>
            )}

            {studentTab === 'RIWAYAT' && (
                <div className="space-y-4">
                    {filteredReports.length > 0 ? (
                        filteredReports.map((report) => (
                             <div key={report.id} className="glass-effect-dark-card rounded-xl shadow-sm p-4 border border-slate-700">
                                <div className="flex justify-between items-start mb-2">
                                    <span className={`px-2 py-1 text-xs font-bold uppercase rounded-md tracking-wider border ${
                                        report.category === 'BULLYING' 
                                        ? 'bg-red-50 text-red-600 border-red-100' 
                                        : 'bg-orange-50 text-orange-600 border-orange-100'
                                    }`}>
                                        {report.category === 'BULLYING' ? 'Bullying' : 'Peristiwa'}
                                    </span>
                                    <span className={`px-2 py-1 text-[10px] font-bold uppercase rounded-full border ${
                                        report.status === 'RESOLVED' 
                                        ? 'bg-green-100 text-green-700 border-green-200' 
                                        : 'bg-yellow-100 text-yellow-700 border-yellow-200'
                                    }`}>
                                        {report.status === 'RESOLVED' ? 'Selesai' : 'Proses'}
                                    </span>
                                </div>
                                <h4 className="font-bold text-slate-100 text-sm mb-1">
                                    {getIncidentLabel(report.incidentType)}
                                </h4>
                                <p className="text-xs text-slate-400 mb-3">
                                    {format(report.incidentDate, 'd MMM yyyy, HH:mm', { locale: id })}
                                </p>
                                <p className="text-slate-300 text-sm line-clamp-2 bg-slate-900/30 p-2 rounded-lg border border-slate-700">
                                    {report.description}
                                </p>
                             </div>
                        ))
                    ) : (
                        <div className="text-center py-10">
                            <div className="w-12 h-12 bg-slate-800/50 rounded-full flex items-center justify-center mx-auto mb-3">
                                <Clock className="w-6 h-6 text-gray-400" />
                            </div>
                            <h3 className="text-slate-100 font-medium text-sm">Belum ada riwayat</h3>
                            <p className="text-xs text-slate-400 mt-1">
                                Laporan yang Anda kirim akan muncul di sini.
                            </p>
                        </div>
                    )}
                </div>
            )}
        </div>
      </div>
    );
  }

  // ADMIN VIEW
  if (user?.role === "admin" || user?.role === "super_admin") {
    const totalBullying = scopedReports.filter(r => (r.category || 'BULLYING') === 'BULLYING').length;
    const totalIncident = scopedReports.filter(r => r.category === 'INCIDENT').length;
    const totalResolved = scopedReports.filter(r => r.status === 'RESOLVED' || r.status === 'CLOSED').length;
    const totalPending = scopedReports.filter(r => r.status === 'PENDING' || r.status === 'INVESTIGATING').length;

    return (
      <div className="min-h-screen bg-slate-900/30 p-6 space-y-6">
        <div className="flex flex-col gap-2">
          <h1 className="text-2xl font-bold text-slate-100">Layanan Aduan</h1>
          <p className="text-sm text-slate-400">
            Laporan masuk dari siswa terkait bullying dan peristiwa lainnya.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <div className="glass-effect-dark-card rounded-lg shadow-sm border border-slate-700 p-4">
            <p className="text-xs font-medium text-slate-400">Total Bullying</p>
            <p className="mt-1 text-2xl font-bold text-slate-100">{totalBullying}</p>
          </div>
          <div className="glass-effect-dark-card rounded-lg shadow-sm border border-slate-700 p-4">
            <p className="text-xs font-medium text-slate-400">Total Peristiwa</p>
            <p className="mt-1 text-2xl font-bold text-slate-100">{totalIncident}</p>
          </div>
          <div className="glass-effect-dark-card rounded-lg shadow-sm border border-slate-700 p-4">
            <p className="text-xs font-medium text-slate-400">Belum Ditangani</p>
            <p className="mt-1 text-2xl font-bold text-red-600">{totalPending}</p>
          </div>
          <div className="glass-effect-dark-card rounded-lg shadow-sm border border-slate-700 p-4">
            <p className="text-xs font-medium text-slate-400">Sudah Selesai</p>
            <p className="mt-1 text-2xl font-bold text-green-600">{totalResolved}</p>
          </div>
        </div>

        <div className="glass-effect-dark-card rounded-lg shadow-sm border border-slate-700">
          <div className="border-b border-slate-700 px-4 py-3 flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
            <div className="flex items-center gap-4">
              <div className="inline-flex rounded-full bg-blue-50 p-1 text-blue-600">
                <ShieldAlert className="w-5 h-5" />
              </div>
              <div>
                <p className="text-sm font-semibold text-slate-100">Daftar Laporan Masuk</p>
                <p className="text-xs text-slate-400">
                  Klik tombol status untuk menandai laporan sudah ditangani.
                </p>
              </div>
            </div>
            <div className="flex flex-col gap-2 md:flex-row md:items-center md:gap-4">
              <div className="inline-flex rounded-full bg-slate-800/50 p-1">
                <button
                  onClick={() => setActiveTab('BULLYING')}
                  className={`px-3 py-1.5 text-xs font-semibold rounded-full ${
                    activeTab === 'BULLYING'
                      ? 'bg-blue-600 text-white'
                      : 'text-slate-400'
                  }`}
                >
                  Lapor Bullying
                </button>
                <button
                  onClick={() => setActiveTab('INCIDENT')}
                  className={`px-3 py-1.5 text-xs font-semibold rounded-full ${
                    activeTab === 'INCIDENT'
                      ? 'bg-blue-600 text-white'
                      : 'text-slate-400'
                  }`}
                >
                  Lapor Peristiwa
                </button>
              </div>
              <div className="flex flex-wrap items-center gap-2">
                <div className="inline-flex rounded-full bg-slate-800/50 p-1">
                  <button
                    onClick={() => setStatusFilter('ALL')}
                    className={`px-3 py-1.5 text-xs font-semibold rounded-full ${
                      statusFilter === 'ALL'
                        ? 'bg-gray-900 text-white'
                        : 'text-slate-400'
                    }`}
                  >
                    Semua
                  </button>
                  <button
                    onClick={() => setStatusFilter('PENDING')}
                    className={`px-3 py-1.5 text-xs font-semibold rounded-full ${
                      statusFilter === 'PENDING'
                        ? 'bg-yellow-500 text-white'
                        : 'text-slate-400'
                    }`}
                  >
                    Belum
                  </button>
                  <button
                    onClick={() => setStatusFilter('INVESTIGATING')}
                    className={`px-3 py-1.5 text-xs font-semibold rounded-full ${
                      statusFilter === 'INVESTIGATING'
                        ? 'bg-blue-600 text-white'
                        : 'text-slate-400'
                    }`}
                  >
                    Proses
                  </button>
                  <button
                    onClick={() => setStatusFilter('RESOLVED')}
                    className={`px-3 py-1.5 text-xs font-semibold rounded-full ${
                      statusFilter === 'RESOLVED'
                        ? 'bg-green-600 text-white'
                        : 'text-slate-400'
                    }`}
                  >
                    Selesai
                  </button>
                  <button
                    onClick={() => setStatusFilter('CLOSED')}
                    className={`px-3 py-1.5 text-xs font-semibold rounded-full ${
                      statusFilter === 'CLOSED'
                        ? 'bg-slate-900/300 text-white'
                        : 'text-slate-400'
                    }`}
                  >
                    Ditutup
                  </button>
                </div>

                <div className="relative">
                  <select
                    value={classFilter}
                    onChange={(e) => setClassFilter(e.target.value)}
                    className="pl-3 pr-8 py-1.5 text-xs border border-slate-700 rounded-full glass-effect-dark-card text-slate-300 focus:outline-none focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
                  >
                    <option value="ALL">Semua Kelas</option>
                    {classes
                      .slice()
                      .sort((a, b) => {
                        const normalize = (name: string) =>
                          name
                            .replace("VII", "7")
                            .replace("VIII", "8")
                            .replace("IX", "9")
                            .replace("-", "");
                        const nameA = normalize(a.name);
                        const nameB = normalize(b.name);
                        return nameA.localeCompare(nameB, undefined, { numeric: true, sensitivity: 'base' });
                      })
                      .map((cls) => (
                        <option key={cls.id} value={cls.name}>
                          {cls.name}
                        </option>
                      ))}
                  </select>
                </div>
                <button
                  onClick={handleExportAdmin}
                  className="inline-flex items-center gap-2 px-3 py-1.5 text-xs font-semibold rounded-full bg-green-600 text-white hover:bg-green-700"
                >
                  Export Excel
                </button>
              </div>
            </div>
          </div>

          {classRecap && (
            <div className="px-4 pt-3 pb-2 border-b border-slate-700 bg-slate-900/30/60">
              <div className="flex flex-wrap items-center gap-2 text-[11px] text-slate-300">
                <span className="font-semibold mr-1">
                  Rekap Kelas {classFilter}:
                </span>
                <span className="px-2 py-0.5 rounded-full bg-gray-200 text-gray-800">
                  Total {classRecap.total}
                </span>
                <span className="px-2 py-0.5 rounded-full bg-red-50 text-red-700 border border-red-200">
                  Bullying {classRecap.bullying}
                </span>
                <span className="px-2 py-0.5 rounded-full bg-orange-50 text-orange-700 border border-orange-200">
                  Peristiwa {classRecap.incident}
                </span>
                <span className="px-2 py-0.5 rounded-full bg-yellow-50 text-yellow-700 border border-yellow-200">
                  Belum {classRecap.pending}
                </span>
                <span className="px-2 py-0.5 rounded-full bg-blue-50 text-blue-700 border border-blue-200">
                  Proses {classRecap.investigating}
                </span>
                <span className="px-2 py-0.5 rounded-full bg-green-50 text-green-700 border border-green-200">
                  Selesai {classRecap.resolved}
                </span>
                <span className="px-2 py-0.5 rounded-full bg-gray-200 text-gray-800">
                  Ditutup {classRecap.closed}
                </span>
              </div>
            </div>
          )}

          <div className="p-4 space-y-3 max-h-[70vh] overflow-y-auto">
            {adminReports.map((report) => (
              <div key={report.id} className="border border-slate-700 rounded-lg p-4 hover:border-blue-200 transition-colors">
                <div className="flex justify-between items-start mb-2">
                  <div className="flex items-center gap-2">
                    <span className={`px-2 py-1 text-[10px] font-bold uppercase rounded-md tracking-wider ${
                      report.category === 'BULLYING'
                        ? 'bg-red-50 text-red-600 border border-red-200'
                        : 'bg-orange-50 text-orange-600 border border-orange-200'
                    }`}>
                      {report.category === 'BULLYING' ? 'Bullying' : 'Peristiwa'}
                    </span>
                    <span className="px-2 py-1 text-[10px] font-semibold rounded-full border border-slate-700 text-slate-400">
                      {getIncidentLabel(report.incidentType) || 'Umum'}
                    </span>
                  </div>
                  <span className="text-xs text-gray-400">
                    {format(report.incidentDate, 'd MMM yyyy, HH:mm', { locale: id })}
                  </span>
                </div>

                <p className="text-sm text-gray-800 mb-3 line-clamp-2">
                  {report.description}
                </p>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-2 text-xs mb-3">
                  <div>
                    <span className="font-semibold text-slate-300">Pelapor</span>
                    <p className="text-slate-400">{report.reporterName}</p>
                  </div>
                  <div>
                    <span className="font-semibold text-slate-300">Korban</span>
                    <p className="text-slate-400">{report.victimName || '-'}</p>
                  </div>
                  <div>
                    <span className="font-semibold text-slate-300">Pelaku</span>
                    <p className="text-slate-400">{report.perpetratorName || '-'}</p>
                  </div>
                </div>

                <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-2">
                  <div>
                    <span className="text-[11px] font-semibold text-slate-300 mr-2">Status Penanganan:</span>
                    <span className={`inline-flex items-center px-2 py-0.5 rounded-full text-[11px] font-semibold border ${
                      report.status === 'RESOLVED' || report.status === 'CLOSED'
                        ? 'bg-green-50 text-green-700 border-green-200'
                        : report.status === 'INVESTIGATING'
                        ? 'bg-blue-50 text-blue-700 border-blue-200'
                        : 'bg-yellow-50 text-yellow-700 border-yellow-200'
                    }`}>
                      {report.status === 'RESOLVED' || report.status === 'CLOSED'
                        ? 'Selesai'
                        : report.status === 'INVESTIGATING'
                        ? 'Sedang Ditangani'
                        : 'Belum Ditangani'}
                    </span>
                  </div>
                  <div className="flex gap-2">
                    <button
                      onClick={() => void updateAdminReportStatus(report.id, 'PENDING')}
                      className={`px-3 py-1.5 rounded-full text-xs font-semibold border transition-colors ${
                        report.status === 'PENDING'
                          ? 'glass-effect-dark-card border-gray-300 text-slate-400'
                          : 'glass-effect-dark-card border-slate-700 text-gray-400 hover:bg-slate-900/30'
                      }`}
                    >
                      Tandai Belum
                    </button>
                    <button
                      onClick={() => void updateAdminReportStatus(report.id, 'INVESTIGATING')}
                      className={`px-3 py-1.5 rounded-full text-xs font-semibold border transition-colors ${
                        report.status === 'INVESTIGATING'
                          ? 'bg-blue-600 border-blue-600 text-white'
                          : 'glass-effect-dark-card border-blue-200 text-blue-600 hover:bg-blue-50'
                      }`}
                    >
                      Proses
                    </button>
                    <button
                      onClick={() => void updateAdminReportStatus(report.id, 'RESOLVED')}
                      className={`px-3 py-1.5 rounded-full text-xs font-semibold border transition-colors flex items-center gap-1 ${
                        report.status === 'RESOLVED'
                          ? 'bg-green-600 border-green-600 text-white'
                          : 'glass-effect-dark-card border-green-200 text-green-600 hover:bg-green-50'
                      }`}
                    >
                      {report.status === 'RESOLVED' && <Check className="w-3 h-3" />}
                      Selesai
                    </button>
                    <button
                      onClick={() => void updateAdminReportStatus(report.id, 'CLOSED')}
                      className={`px-3 py-1.5 rounded-full text-xs font-semibold border transition-colors ${
                        report.status === 'CLOSED'
                          ? 'bg-gray-700 border-gray-700 text-white'
                          : 'glass-effect-dark-card border-gray-300 text-slate-400 hover:bg-slate-900/30'
                      }`}
                    >
                      Tutup
                    </button>
                  </div>
                </div>
              </div>
            ))}

            {adminReports.length === 0 && (
              <div className="flex flex-col items-center justify-center py-12 text-center">
                <div className="w-12 h-12 bg-slate-800/50 rounded-full flex items-center justify-center mb-3">
                  <ShieldAlert className="w-6 h-6 text-gray-400" />
                </div>
                <h3 className="text-sm font-medium text-slate-100">Belum ada laporan</h3>
                <p className="text-xs text-slate-400 mt-1">
                  Belum ada laporan {activeTab === 'BULLYING' ? 'bullying' : 'peristiwa'} yang masuk.
                </p>
              </div>
            )}
          </div>
        </div>
      </div>
    );
  }

  // TEACHER VIEW
  return (
    <div className="min-h-screen bg-slate-900/30 -mx-4 -mt-4 sm:-mx-8 sm:-mt-8">
      {/* Header */}
      <div className="bg-blue-600 px-4 pt-6 pb-0 shadow-md">
        <div className="flex items-center text-white mb-4">
          <button onClick={() => router.back()} className="mr-4">
            <ArrowLeft className="w-6 h-6" />
          </button>
          <div>
            <h1 className="text-xl font-bold">Layanan Aduan</h1>
            <p className="text-blue-100 text-sm">
              {teacherClassName ? `Wali Kelas ${teacherClassName}` : 'Guru'}
            </p>
          </div>
        </div>

        {/* Tabs */}
        <div className="flex text-center">
          <button
            onClick={() => setActiveTab('BULLYING')}
            className={`flex-1 pb-3 text-sm font-medium border-b-2 transition-colors ${
              activeTab === 'BULLYING'
                ? 'border-white text-white'
                : 'border-transparent text-blue-200 hover:text-white'
            }`}
          >
            Lapor Bullying
          </button>
          <button
            onClick={() => setActiveTab('INCIDENT')}
            className={`flex-1 pb-3 text-sm font-medium border-b-2 transition-colors ${
              activeTab === 'INCIDENT'
                ? 'border-white text-white'
                : 'border-transparent text-blue-200 hover:text-white'
            }`}
          >
            Lapor Peristiwa
          </button>
        </div>
      </div>

      {/* List Content */}
      <div className="p-4 space-y-4">
        {filteredReports.map((report) => (
          <div key={report.id} className="glass-effect-dark-card rounded-xl shadow-sm p-4 border border-slate-700">
            {/* Header Card: Chip + Date */}
            <div className="flex justify-between items-start mb-2">
              <span className="px-2 py-1 bg-gray-200 text-slate-300 text-xs font-bold uppercase rounded-md tracking-wider border border-gray-300">
                {getIncidentLabel(report.incidentType) || 'UMUM'}
              </span>
              <span className="text-xs text-gray-400">
                {format(report.incidentDate, 'd MMM yyyy, HH:mm', { locale: id })}
              </span>
            </div>

            {/* Description */}
            <p className="text-slate-100 text-sm mb-4 line-clamp-2">
              {report.description}
            </p>

            {/* Details */}
            <div className="space-y-1 mb-4 border-t border-b border-gray-50 py-3">
              <div className="grid grid-cols-[80px_1fr] text-xs">
                <span className="font-bold text-slate-100">Pelapor:</span>
                <span className="text-slate-400 uppercase font-medium">{report.reporterName}</span>
              </div>
              <div className="grid grid-cols-[80px_1fr] text-xs">
                <span className="font-bold text-slate-100">Korban:</span>
                <span className="text-slate-400 uppercase font-medium">{report.victimName || '-'}</span>
              </div>
              <div className="grid grid-cols-[80px_1fr] text-xs">
                <span className="font-bold text-slate-100">Pelaku:</span>
                <span className="text-slate-400 uppercase font-medium">{report.perpetratorName || '-'}</span>
              </div>
            </div>

            <div>
              <p className="text-xs font-bold text-slate-100 mb-2">Status Penanganan:</p>
              <div className="flex gap-3">
                <button 
                  onClick={() => updateReportStatus(report.id, 'PENDING')}
                  className={`flex-1 py-2.5 rounded-full text-xs font-bold border transition-colors ${
                    report.status === 'PENDING'
                      ? 'glass-effect-dark-card border-gray-300 text-slate-400 shadow-sm'
                      : 'glass-effect-dark-card border-slate-700 text-gray-400 hover:bg-slate-900/30'
                  }`}
                >
                  Belum
                </button>
                <button 
                  onClick={() => updateReportStatus(report.id, 'INVESTIGATING')}
                  className={`flex-1 py-2.5 rounded-full text-xs font-bold border transition-colors ${
                    report.status === 'INVESTIGATING'
                      ? 'bg-blue-600 border-blue-600 text-white shadow-md'
                      : 'glass-effect-dark-card border-blue-200 text-blue-600 hover:bg-blue-50'
                  }`}
                >
                  Proses
                </button>
                <button 
                  onClick={() => updateReportStatus(report.id, 'RESOLVED')}
                  className={`flex-1 py-2.5 rounded-full text-xs font-bold border transition-colors flex items-center justify-center gap-1 ${
                    report.status === 'RESOLVED'
                      ? 'bg-green-500 border-green-500 text-white shadow-md'
                      : 'glass-effect-dark-card border-slate-700 text-gray-400 hover:bg-green-50 hover:text-green-600 hover:border-green-200'
                  }`}
                >
                  {report.status === 'RESOLVED' && <Check className="w-3 h-3" />}
                  Selesai
                </button>
              </div>
            </div>
          </div>
        ))}
        
        {filteredReports.length === 0 && (
          <div className="flex flex-col items-center justify-center py-20 text-center">
            <div className="w-16 h-16 bg-slate-800/50 rounded-full flex items-center justify-center mb-4">
              <ShieldAlert className="w-8 h-8 text-gray-400" />
            </div>
            <h3 className="text-slate-100 font-medium">Tidak ada laporan</h3>
            <p className="text-sm text-slate-400 mt-1">
              Belum ada laporan {activeTab === 'BULLYING' ? 'bullying' : 'peristiwa'} yang masuk.
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
